name: Flutter Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Flutter dev channel (Dart 3.5+)
      - name: Install Flutter dev
        run: |
          git clone -b dev https://github.com/flutter/flutter.git $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      # Step 3: Verify Flutter & Dart version
      - name: Check Flutter & Dart versions
        run: |
          flutter --version
          dart --version

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web --release --base-href /

      # Step 6: Deploy to GitHub Pages
      - name: Deploy web to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
